feat: Vol 4754 bump static analysis to level 5
dvsa/olcs-transfer pull request #59
Opened 2024-03-20 16:41 UTC by sanakhandvsa

## Description
Ticket: [VOL-4754](https://dvsa.atlassian.net/browse/VOL-4754)
fix(test): Fix miscellaneous PHPStan errors

- Bump PHPStan level to 5
- Included vendor/phpstan/phpstan-mockery/extension.neon for mocking in tests
- Resolved PHPStan errors in test files

feat: Fix PHPStan errors in source code and test files

- Correct type mismatches
- Ensure properties are initialized before use
- Resolve undefined method calls

Related issue: [JIRA_TICKET_NUMBER](LINK_TO_JIRA_TICKET)

## Before submitting (or marking as "ready for review")

- [ ] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [ ] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2024-03-25 17:17 UTC, JoshuaLicense commented on src/Service/CacheEncryption.php
> -        return $cacheConfig;
Why are we removing all this?

2024-03-26 09:08 UTC, sanakhandvsa commented on src/FieldType/Traits/IrhpPermitRangeTo.php
> +    protected int $toNo = 0;
addded * @var int|null or else it was suggesting int cannot be null

2024-03-26 09:14 UTC, sanakhandvsa commented on src/FieldType/Traits/IrhpPermitRangeTo.php
> +    protected int $toNo = 0;
This was added due to 
`Error: Typed property Dvsa\Olcs\Transfer\Command\IrhpPermitRange\Update::$toNo must not be accessed before initialization`

2024-03-26 09:30 UTC, sanakhandvsa commented on src/Command/Trailer/UpdateTrailer.php
> +    protected string $trailerNo = '';
```
8) Dvsa\OlcsTest\Transfer\Command\Trailer\UpdateTrailerTest::testStructure
Error: Typed property Dvsa\Olcs\Transfer\Command\Trailer\UpdateTrailer::$trailerNo must not be accessed before initialization
```
This change was made in response to a failing test case, specifically the error message indicating that the property UpdateTrailer::$trailerNo was accessed before initialization. 
By ensuring that $trailerNo is always initialized with an empty string, we prevent this error from occurring and ensure the proper initialization of the property before any access attempts, addressing the failing test case and resolving the associated issue.

2024-03-26 10:20 UTC, JoshuaLicense commented on src/FieldType/Traits/IrhpPermitRangeTo.php
> +    protected int $toNo = 0;
Try to avoid updating _source_ code just to fix a test - it's an unnecessary risk.

2024-03-26 14:49 UTC, sanakhandvsa commented on src/FieldType/Traits/IrhpPermitRangeTo.php
> +    protected int $toNo = 0;
Ok, Reverted back

2024-03-26 15:01 UTC, sanakhandvsa commented on src/Command/Trailer/UpdateTrailer.php
> +    protected string $trailerNo = '';
Fix the test instead of src code

2024-03-26 15:07 UTC, sanakhandvsa commented on src/FieldType/Traits/IrhpPermitType.php
> +    protected string $irhpPermitType = '';
Reverted

2024-03-26 15:34 UTC, sanakhandvsa commented on src/Util/Annotation/Partial.php
> + * @method mixed getComposedObject()
replaced with @mixin

2024-03-26 15:42 UTC, sanakhandvsa commented on src/Util/StructuredInput.php
> +        return $this;
interface InputInterface method setAllowEmpty return $this
/**
     * @deprecated 2.4.8 Add Laminas\Validator\NotEmpty validator to the ValidatorChain and set this to `true`.
     *
     * @param bool $allowEmpty
     * @return $this
     */
    public function setAllowEmpty($allowEmpty);

2024-03-26 15:58 UTC, sanakhandvsa commented on src/Util/StructuredInput.php
> +        return $this;
**Explanation for Changing Return Type in setErrorMessage Method:**

In our StructuredInput class, we implement both the InputInterface and InputFilterInterface interfaces. The setErrorMessage method defined in InputInterface specifies that it should return $this, indicating that it returns the instance of the object itself. Therefore, we adjusted the return type in our implementation to ensure consistency with the interface contract. This change maintains clarity and adherence to the specified interface requirements.

2024-03-26 16:09 UTC, sanakhandvsa commented on src/Validators/DateInFuture.php
> +     * @return AbstractValidator&static
**Explanation for ERROR: LessSpecificImplementedReturnType:**

The error is originating from the **DateInFuture** class, specifically from the overridden setOptions method. This error occurs because the return type declared in **DateInFuture::setOptions** is less specific than the return type inherited from the parent class AbstractValidator::setOptions. The parent class method specifies a return type of **AbstractValidator&static**, indicating an instance of **AbstractValidator** or a subclass, while the **DateInFuture::setOptions** method specifies a return type of **DateInFuture**.

To resolve this error, we should ensure that the return type declared in **DateInFuture::setOption**s is compatible with the return type declared in the parent class. We may need to adjust the return type declaration in **DateInFuture::setOptions** to match or be more specific than the return type declared in the parent class.

2024-03-26 16:28 UTC, sanakhandvsa commented on src/Validators/EmailAddress.php
> +            $allow = (array) $this->getAllow();
Previously, the code attempted to instantiate the **Hostname** validator using the **$this->getAllow()** method, which returned an **int** value. To fix this, I modified the code to ensure that the argument passed to the **Hostname** constructor is always of type **array**.
either **cast** directly or 

achieved this by checking if the return value of **$this->getAllow()** is already an array using the **is_array()** function. If it is, I assigned it directly to the **$options** variable. Otherwise, I created a new array with **$allow** as its only element.

```
$allow = $this->getAllow();
$options = is_array($allow) ? $allow : [$allow];
```

2024-03-27 09:01 UTC, sanakhandvsa commented on src/Service/CacheEncryption.php
> -        return $cacheConfig;
I removed the lines that set the `$cacheConfig` variable directly from the `self::CUSTOM_CACHE_TYPE` array and checked for the existence of keys `'mode'` and `'ttl'`. This was done because the subsequent lines already access these keys from the same array without checking for their existence. Since these keys are required for the cache configuration and they are not nullable according to the type declaration of `self::CUSTOM_CACHE_TYPE`, there is no need for additional checks. Removing this redundant code simplifies the function and improves readability without compromising functionality.

2024-03-27 09:27 UTC, sanakhandvsa commented on test/Validators/ValidateEachTest.php
> +        $this->assertArrayHasKey('0.notDigits', $validator->getMessages());
added constant , self::NOT_DIGITS

2024-04-05 09:48 UTC, fibble commented on src/Service/CacheEncryption.php
> -        return $cacheConfig;
This removal seems valid, checking for elements defined in the const that wont be missing.

2024-04-05 09:48 UTC, fibble commented on src/Validators/EmailAddress.php
> +            $allow = (array) $this->getAllow();
Supressing, upstream handles non-array inputs so cast not required.

2024-04-08 07:56 UTC, JoshuaLicense requested changes

2024-04-08 07:56 UTC, JoshuaLicense commented on phpstan.neon.dist
> +        path: %currentWorkingDirectory%/src/Util/StructuredInput.php
Can we just fix this instead of ignoring it?

2024-04-08 07:56 UTC, JoshuaLicense commented on src/FieldType/Traits/CaseType.php
> +     * @return String|null
```suggestion
     * @return string|null
```

2024-04-08 07:56 UTC, JoshuaLicense commented on src/FieldType/Traits/Notes.php
> +     * @return String
```suggestion
     * @return string
```

2024-04-08 07:56 UTC, JoshuaLicense commented on src/FieldType/Traits/PresidedByRole.php
> +     * @return String
```suggestion
     * @return string
```

2024-04-08 07:56 UTC, JoshuaLicense commented on src/Query/Publication/PublishedList.php
> +     * @return string|null|false
`false` is a PHP 8.2 return type. Seems strange that this would return a boolean though, can we double-check this type please?

2024-04-08 07:56 UTC, JoshuaLicense commented on src/Util/Annotation/Partial.php
> + * @mixin mixed getComposedObject()
This isn't valid.

https://phpstan.org/writing-php-code/phpdocs-basics#mixins

2024-04-08 07:56 UTC, JoshuaLicense commented on src/Util/StructuredInput.php
> +     * @phpstan-ignore-next-line
Lets fix these instead of ignoring please.

2024-04-08 07:56 UTC, JoshuaLicense commented on src/Validators/Postcode.php
> +     * @return AbstractValidator&static
Why `AbstractValidator&static`?

2024-04-08 07:56 UTC, JoshuaLicense commented on test/Validators/ValidateEachTest.php
> +        $result = $validator->isValid('foo'); /** @phpstan-ignore-line This test intentionally provides incorrect input */
This is testing vendor code inside: `vendor/laminas/laminas-validator/src/IsCountable.php`. Lets remove this test completely.

2024-04-08 07:56 UTC, JoshuaLicense commented on test/Validators/ValidateEachTest.php
> +        $validator->isValid('foo'); /** @phpstan-ignore-line This test intentionally provides incorrect input */
Same for this, we don't need to test for this, Laminas already are.

2024-04-08 10:26 UTC, JoshuaLicense requested changes
Looks much better!

2024-04-08 10:26 UTC, JoshuaLicense commented on src/FieldType/Traits/CaseType.php
> +     * @var ?String
```suggestion
     * @var ?string
```

2024-04-08 10:26 UTC, JoshuaLicense commented on src/FieldType/Traits/IrhpPermitType.php
> +    public function getIrhpPermitType(): string
If `int` was returned before, how come this is now `string`? This seems risky.

2024-04-08 10:26 UTC, JoshuaLicense commented on src/Result/Auth/ChangeExpiredPasswordResult.php
> +    protected $identity;
How come we've lost the type?

2024-04-08 10:26 UTC, JoshuaLicense commented on src/Util/StructuredInput.php
> +     * @return self&static
Why both?

Applies to a bunch more in this/other files.

2024-04-08 10:26 UTC, JoshuaLicense commented on src/Validators/DateCompare.php
> +     * @return AbstractValidator&static
```suggestion
     * @return self
```

Would this work?

2024-04-08 11:09 UTC, fibble commented on src/FieldType/Traits/IrhpPermitType.php
> +    public function getIrhpPermitType(): string
Yeah few bits changed before i picked this up I hadnt spotted. changing back, thanks

2024-04-08 11:17 UTC, ilindsay approved these changes

2024-04-08 11:21 UTC, JoshuaLicense commented on src/Util/StructuredInput.php
> +     * @return self&static
What about just `static`?

2024-04-08 11:43 UTC, JoshuaLicense approved these changes

2024-04-08 14:03 UTC, wadedvsa approved these changes

2024-04-08 14:25 UTC, merged